### ISSUE TITLE
Jargons Editor Login Error caused by Invalid Cookie Name

### ISSUE THREAD

**Issue by babblebey** [jargonsdev/jargons.dev#109]
The Jargons Editor login functionality is currently broken due to an invalid naming convention for the cookie storing the session login access token. The cookie name `jargon.dev:token` is causing issues and needs to be renamed for consistency and proper functionality.  

_Weird stuff is that this was working with this naming format in the initial, I wonder what changed_ 😆🤣😆, I guess we gotta follow standard now, as stated [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#attributes)

#### Actions to take  
- Rename the cookie storing the access token from `jargon.dev:token` to `jargonsdevToken`.  
- Update all relevant instances of this cookie name in the codebase.  
- Ensure login functionality works as expected after the fix.  

#### Changes Required  
The following files need to be updated to reflect the new cookie name:  
- `src/lib/actions/do-auth.js`  
- `src/lib/actions/do-contribution-stats.js`  
- `src/lib/actions/do-edit-word.js`  
- `src/pages/api/dictionary.js`  

### Expected Outcome  
After implementing these changes:
1. The Jargons Editor login should function correctly.  
2. The cookie storing the access token should use the new name `jargonsdevToken`.

**Comment by ShyneADL** [comment]
AppID isn't in the .env.example and it's required to load the editor route locally, how do I get it?

**Comment by babblebey** [comment]
Did you skip the `dev/setup` script, when you're setting up your local dev environment?? 🤔

Run the script `npm run setup`, it starts a flow that guides you to creating the App.

See more in the doc here https://github.com/jargonsdev/jargons.dev/blob/main/dev%2FREADME.md
