### ISSUE TITLE
Build: Move Tailwind CSS to `devDependencies`

### ISSUE THREAD

**Issue by babblebey** [jargonsdev/jargons.dev#19]
Currently, Tailwind CSS is listed as a dependency in `package.json`. To align with our development practices, we should move Tailwind CSS to `devDependencies`.

**Steps:**
1. Open `package.json` file.
2. Locate the `"dependencies"` section.
3. Find the entry for `"tailwindcss"` and cut it.
4. Scroll down to the `"devDependencies"` section.
5. Paste the `"tailwindcss"` entry under `"devDependencies"`.
6. Save the `package.json` file.

**Additional Steps:**

7. Run `npm install` to update the `package-lock.json` file with the changes made to `package.json`.

**Additional Note:**
- Moving Tailwind CSS to `devDependencies` ensures that it is only installed in the development environment, reducing the package size in production builds.
- This should be easy 😉, feel free to ask question if you have any challenges following through the steps

**Comment by amiabl-programr** [comment]
Hi, @babblebey please assign me to this

**Comment by babblebey** [comment]
Hey @amiabl-programr, you have been assigned an issue and can have just one at a time 😉

**Comment by amiabl-programr** [comment]
Alright

**Comment by amiabl-programr** [comment]
Can I work on this?
