### ISSUE TITLE
Enhancement: Rename Project in package.json

### ISSUE THREAD

**Issue by babblebey** [jargonsdev/jargons.dev#20]
The project was initially named "Dictionry" (a fun typo!), but the name has since been changed to "jargons.dev". Let's update the `name` field in `package.json` to reflect this change.

**Steps:**
1. Open `package.json` file.
2. Locate the `"name"` field.
3. Change the value from `"dictionry"` to `"jargons.dev"`.
4. Save the `package.json` file.

**Additional Steps:**

5. Run `npm install` to update the `package-lock.json` file with the changes made to `package.json`.

**Background Story 😉:**

When the project was first started by @babblebey (that wasn't me haha 😆), it was humorously named "Dictionry" due to a typo. Despite its quirky origins, the name stuck until a decision was made to change it to "jargons.dev".

**Note:**
- Changing the `name` field in `package.json` helps maintain consistency and clarity in project naming.

**Comment by amiabl-programr** [comment]
Hi @babblebey, can you assign me to this issue?
