### ISSUE TITLE
Build: Move `"@types/react"` to `devDependencies`

### ISSUE THREAD

**Issue by babblebey** [jargonsdev/jargons.dev#21]
Currently, `"@types/react"` is listed as a dependency in `package.json`. To align with good development practices, we should move `"@types/react"` to `devDependencies`.

**Steps:**
1. Open `package.json` file.
2. Locate the `"dependencies"` section.
3. Find the entry for `"@types/react"` and cut it.
4. Scroll down to the `"devDependencies"` section.
5. Paste the `"@types/react"` entry under `"devDependencies"`.
6. Save the `package.json` file.

**Additional Steps:**

7. Run `npm install` to update the `package-lock.json` file with the changes made to `package.json`.

**Additional Note:**
- Moving `"@types/react"` to `devDependencies` ensures that it is only installed in the development environment, reducing the package size in production builds.
- This should be easy yea 😁 , feel free to ask question if you have any challenges following through the steps

**Comment by DevYoma** [comment]
Hello @babblebey, can I work on this

**Comment by babblebey** [comment]
Hey @DevYoma, please deal 😉
