### ISSUE TITLE
Build: Move `"@types/react-dom"` to `devDependencies`

### ISSUE THREAD

**Issue by babblebey** [jargonsdev/jargons.dev#22]
Currently, `"@types/react-dom"` is listed as a dependency in `package.json`. To align with good development practices, we should move `"@types/react-dom"` to `devDependencies`.

**Steps:**
1. Open `package.json` file.
2. Locate the `"dependencies"` section.
3. Find the entry for `"@types/react-dom"` and cut it.
4. Scroll down to the `"devDependencies"` section.
5. Paste the `"@types/react-dom"` entry under `"devDependencies"`.
6. Save the `package.json` file.

**Additional Steps:**

7. Run `npm install` to update the `package-lock.json` file with the changes made to `package.json`.

**Additional Note:**
- Moving `"@types/react-dom"` to `devDependencies` ensures that it is only installed in the development environment, reducing the package size in production builds.
- This should be easy for sure 😀 , feel free to ask question if you have any challenges following through the steps

**Comment by babblebey** [comment]
> Done this already, will include in my next PR

Tiny changes is the best 😉, a PR for a Single Issue

**Comment by chiomalovet** [comment]
is this resolved yet?

**Comment by chiomalovet** [comment]
Can i work on  this?

**Comment by babblebey** [comment]
Please do @chiomalovet 

### Quick Note

- Switch back to your `main` branch in your local clone - `git checkout main`
- Pull latest changes to from remote to the `main` - `git pull`
- Then Create a new branch to make this change on 

Write a comment here if you need more clarity on setting up 😉
