### ISSUE TITLE
Remove `@astrojs/node` package from dependencies

### ISSUE THREAD

**Issue by babblebey** [jargonsdev/jargons.dev#44]
The `@astrojs/node` package, which was previously used as an SSR adapter for the project, has been replaced by `@astrojs/vercel`. To clean up the project dependencies, we should remove the `@astrojs/node` package from the project.

**Steps:**
1. Remove the `@astrojs/node` package from the dependencies in the `package.json` file.
2. Run the `npm install` command to update the `package-lock.json` file and remove the `@astrojs/node` package.

**Expected Behavior:**
- The `@astrojs/node` package should be removed from the project dependencies.
- The project should still build and run correctly after removing the `@astrojs/node` package.

**Additional Information:**
- This change is necessary to clean up the project dependencies and ensure that only the required packages are included in the project.

**Comment by amiabl-programr** [comment]
Hi @babblebey, assign me to this

**Comment by babblebey** [comment]
Thanks for taking this @amiabl-programr 🙌🏾

**Comment by amiabl-programr** [comment]
You're welcome 🙌
