### ISSUE TITLE
Extract "Contribution CTA" Component to a Reusable Component

### ISSUE THREAD

**Issue by babblebey** [jargonsdev/jargons.dev#69]
We would like to enhance our codebase by extracting the "Contribution CTA" section currently used in the `/editor/index.astro` and `/browse/[alpha]/[page].astro` files into a standalone reusable component. This will improve code maintainability and reusability.

#### Current Implementation
The "Contribution CTA" section is currently duplicated in both `/editor/index.astro` and `/browse/[alpha]/[page].astro`. Below is the code snippet from the `/editor/index.astro` file:

```html
<!-- Contribution CTA -->
<section class="rounded-lg border shadow-sm">
  <div class="space-y-1.5 p-3 md:p-6 flex flex-col lg:flex-row lg:items-center justify-between gap-4">
    <div class="space-y-1">
      <h3 class="font-semibold tracking-tight text-2xl">Contribute Words</h3>
      <p class="text-sm">
        You can contribute new words to the jargons.dev dictionary.
      </p>
    </div>
    <a
      class="flex items-center w-fit justify-center no-underline px-4 py-2 rounded-md border border-gray-200 bg-white hover:bg-gray-100 text-sm shadow-sm hover:shadow transition-colors"
      href="/editor/new"
    >
      <span>Start Now</span>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width={1.5} stroke="currentColor" class="w-4 h-4">
        <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25" />
      </svg> 
    </a>
  </div>
</section>
```

#### Task
1. **Create a New Component:**
   - Create a new file named `contribution-cta.astro` in the components directory at `src/components`.
   - Move the "Contribution CTA" code into this new file.

2. **Update `/editor/index.astro` and `/browse/[alpha]/[page].astro`:**
   - Replace the existing "Contribution CTA" section in both files with the newly created `contribution-cta.astro` component.

#### Implementation Steps
1. Create a new file `contribution-cta.astro` with the following content:
   ```html
   <section class="rounded-lg border shadow-sm">
     <div class="space-y-1.5 p-3 md:p-6 flex flex-col lg:flex-row lg:items-center justify-between gap-4">
       <div class="space-y-1">
         <h3 class="font-semibold tracking-tight text-2xl">Contribute Words</h3>
         <p class="text-sm">
           You can contribute new words to the jargons.dev dictionary.
         </p>
       </div>
       <a
         class="flex items-center w-fit justify-center no-underline px-4 py-2 rounded-md border border-gray-200 bg-white hover:bg-gray-100 text-sm shadow-sm hover:shadow transition-colors"
         href="/editor/new"
       >
         <span>Start Now</span>
         <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width={1.5} stroke="currentColor" class="w-4 h-4">
           <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25" />
         </svg> 
       </a>
     </div>
   </section>
   ```

2. In the `/editor/index.astro` file, replace the existing "Contribution CTA" section with:
   ```html
   <ContributeCTA />
   ```

3. In the `/browse/[alpha]/[page].astro` file, replace the existing "Contribution CTA" section with:
   ```html
   <ContributeCTA />
   ```

#### Acceptance Criteria
- The `contribution-cta.astro` component is created and contains the extracted code.
- The `/editor/index.astro` and `/browse/[alpha]/[page].astro` files are updated to use the new `contribution-cta.astro` component.
- The application functions as expected with the new component in place.

#### Additional Information
- Feel free to ask for more details or clarifications if needed. This enhancement aims to improve the maintainability and reusability of our code.

**Comment by Bridgetamana** [comment]
Please assign this to me
