### ISSUE TITLE
Add Fixed Height and Scroll to Search Dialog Result

### ISSUE THREAD

**Issue by babblebey** [jargonsdev/jargons.dev#77]
Currently, the search dialog result in the Jargons Editor does not have a fixed height or scroll functionality. This becomes an issue when the search result is extensive, causing it to overflow off the page and making it difficult for users to view all the results. To improve the user experience, we need to add a fixed height to the search dialog result and enable scrolling when the content exceeds the fixed height.

[screencast-localhost_4321-2024.06.07-22_40_17.webm](https://github.com/devjargons/jargons.dev/assets/25631971/c9d035e1-f21b-4812-8962-239f5c31b2e8)

#### Task
1. **Add Fixed Height**: Set a fixed height for the search dialog result div.
2. **Enable Scroll**: Add a vertical scroll bar to the search dialog result when the content exceeds the fixed height.

#### Implementation Steps
1. **Set Fixed Height**:
   - Determine an appropriate fixed height for the search dialog result.
   - Apply the fixed height using CSS to the search dialog result div.

2. **Enable Scroll**:
   - Add CSS properties to enable vertical scrolling for the search dialog result div when the content exceeds the fixed height.

#### Acceptance Criteria
- The search dialog result div should have a fixed height.
- When the content exceeds the fixed height, a vertical scroll bar should appear, allowing users to scroll through the content.

#### Additional Information
- Adding a fixed height and scroll functionality to the search dialog result will ensure that users can easily view and navigate through search results

**Comment by jomefavourite** [comment]
I'd like to take this up

**Comment by babblebey** [comment]
Hey @jomefavourite, have at it 😁

**Comment by jomefavourite** [comment]
PR made
