### ISSUE TITLE
Remove Incorrect 'whirl' Instance from `index.astro` and `login.astro`

### ISSUE THREAD

**Issue by babblebey** [jargonsdev/jargons.dev#97]
It has been identified that an instance of `'whirl'` with the `id` element was mistakenly added in a previous pull request. This needs to be corrected.

### Tasks:

1. **Remove 'whirl' Instance from `index.astro`:**
   - Locate and remove the id property `id="whirl-browse-words"` from line 29 of the `src/pages/index.astro` file.
https://github.com/jargonsdev/jargons.dev/blob/cbf36811989f052b37f934e18ad898b034577466/src/pages/index.astro#L29

2. **Remove 'whirl' Instance from `login.astro`:**
   - Locate and remove the id property `id="whirl-login-btn"` from line 23 of the `src/pages/login.astro` file.
https://github.com/jargonsdev/jargons.dev/blob/cbf36811989f052b37f934e18ad898b034577466/src/pages/login.astro#L23

### Expected Outcome:

The `'whirl'` instance with the `id` element should be removed from the specified lines in both files. The code should function correctly without these unnecessary elements.

**Comment by divineamunega** [comment]
Please assign me to this

**Comment by babblebey** [comment]
Hey @divineamunega, have at it 😉

Feel free to write a comment here if you have any questions or need help with anything during this contribution process 🙏🏾
